// Annota - main.cpp : command line driver.
//
//   annota run   <file.ant>        execute a program            (default)
//   annota check <file.ant>        parse + compile + report annotations
//   annota -e "<code>"             run a snippet
//   options:
//     --dump-tokens        print the token stream
//     --dump-ast           print the parsed program
//     --dump-bc            disassemble the generated bytecode
//     --dump-annotations   print the annotation index (JSON)
//     --contracts          evaluate [[assert]]/[[require]]/[[ensure]]/[[invariant]]
//     --gui                open the view in a real window (requires a Qt build)
//     --gui-shot <path>    render the view to a PNG without opening a window
//     --gui-tree           print the view tree as text
#include "parser.hpp"
#include "module_loader.hpp"
#include "ffi.hpp"
#include "compiler.hpp"
#include "vm.hpp"
#include "builtins.hpp"
#include "gui.hpp"
#include "repl.hpp"
#include "commands.hpp"
#include "analyzer.hpp"
#include <algorithm>
#include <filesystem>
#include <system_error>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>

using namespace annota;

// ---------------------------------------------------------------- utilities
static bool fileExists(const std::string& p) {
    std::FILE* f = std::fopen(p.c_str(), "rb");
    if (!f) return false;
    std::fclose(f);
    return true;
}

static std::string readFile(const std::string& p) {
    std::ifstream in(p, std::ios::binary);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

static std::string dirOf(const std::string& path) {
    size_t q = path.find_last_of("/\\");
    return q == std::string::npos ? std::string(".") : path.substr(0, q);
}

static void printSourceError(const std::string& file, int line, const std::string& msg, bool warning = false) {
    std::fprintf(stderr, "%s: %s: %s\n", file.c_str(), warning ? "warning" : "error", msg.c_str());
    if (line <= 0) return;
    std::ifstream in(file);
    if (!in) return;
    std::string l;
    int n = 1;
    while (std::getline(in, l) && n < line) n++;
    if (n == line) {
        std::fprintf(stderr, "%5d | %s\n", line, l.c_str());
        std::fprintf(stderr, "      | ");
        for (size_t i = 0; i < l.size() && i < 200; i++) std::fputc(' ', stderr);
        std::fprintf(stderr, "^\n");
    }
}

// ---------------------------------------------------------------- module loader

// ---------------------------------------------------------------- disassembler
static void disassemble(const std::shared_ptr<Chunk>& ch, int depth);

static void disassemble(const std::shared_ptr<Chunk>& ch, int depth) {
    std::string pad((size_t)depth * 2, ' ');
    std::printf("%s== function %s (%s) locals=%d params=%d%s ==\n", pad.c_str(), ch->fnName.c_str(),
                ch->file.c_str(), ch->numLocals, (int)ch->params.size(), ch->isMethod ? " method" : "");
    size_t i = 0;
    while (i < ch->code.size()) {
        size_t at = i;
        uint8_t op = ch->code[i++];
        std::string extra;
        int line = (int)ch->lines.size() > (int)at ? ch->lines[at] : 0;
        // operand readers are bounds checked: a malformed chunk must print, not crash
        auto constAt = [&](size_t k) -> const Value& {
            static Value nullv;
            if (k >= ch->consts.size()) return nullv;
            return *(ch->consts.begin() + (long)k);
        };
        auto byteAt = [&](size_t k) -> uint8_t { return k < ch->code.size() ? ch->code[k] : 0; };
        auto u16 = [&]() { uint16_t v = (uint16_t)((byteAt(i) << 8) | byteAt(i + 1)); i += 2; return v; };
        auto s16 = [&]() { int16_t v = (int16_t)((byteAt(i) << 8) | byteAt(i + 1)); i += 2; return v; };
        auto u8 = [&]() { return byteAt(i++); };
        switch (op) {
            case OP_CONST: { uint16_t k = u16(); const Value& v = constAt(k); extra = formatInt(k) + " (" + (v.t == VT::Str ? "\"" + v.o->str + "\"" : std::string(v.typeName())) + ")"; break; }
            case OP_GET_GLOBAL: case OP_SET_GLOBAL: case OP_DEF_GLOBAL: case OP_DEL_GLOBAL:
            case OP_GET_FIELD: case OP_SET_FIELD: { uint16_t k = u16(); extra = constAt(k).o ? constAt(k).o->str : "?"; break; }
            case OP_GET_SUPER: { uint16_t k = u16(); uint16_t c = u16(); extra = constAt(k).o->str + " of class#" + formatInt(c); break; }
            case OP_CLASS: case OP_SUPER_INIT: case OP_CLOSURE: { uint16_t k = u16(); extra = "#" + formatInt(k) + " " + (constAt(k).o && constAt(k).o->klass ? constAt(k).o->klass->name : (constAt(k).o ? constAt(k).o->str : "")); break; }
            case OP_JUMP: case OP_JUMP_IF_FALSE: case OP_JUMP_IF_FALSE_KEEP: case OP_JUMP_IF_TRUE_KEEP:
            case OP_LOOP: case OP_TRY: case OP_ITER_NEXT: { int16_t j = s16(); extra = "-> " + formatInt((int64_t)i + j); break; }
            case OP_JUMP_IF_PROVIDED: { uint8_t p = u8(); int16_t j = s16(); extra = "param " + formatInt(p) + " -> " + formatInt((int64_t)i + j); break; }
            case OP_COLLECT_VARARGS: { uint8_t s = u8(); uint8_t f = u8(); extra = "slot " + formatInt(s) + " fixed " + formatInt(f); break; }
            case OP_BUILD_LIST: case OP_BUILD_TUPLE: case OP_BUILD_NAMED: { uint16_t n = u16(); extra = formatInt(n); break; }
            case OP_GET_LOCAL: case OP_SET_LOCAL: case OP_INIT_LOCAL: case OP_DEL_LOCAL:
            case OP_GET_UPVAL: case OP_SET_UPVAL: case OP_UI_APPEND: { uint8_t s = u8(); extra = formatInt(s); break; }
            case OP_ITER_BIND2: { uint8_t a = u8(); uint8_t b = u8(); extra = formatInt(a) + ", " + formatInt(b); break; }
            case OP_PRINT: { uint8_t n = u8(); uint8_t s = u8(); extra = formatInt(n) + (s ? " with sep" : ""); break; }
            case OP_INT1: { int8_t v = (int8_t)u8(); extra = formatInt(v); break; }
            case OP_NOP: break;
            case OP_LOCAL_ADD_IMM: case OP_LOCAL_SUB_IMM: {
                uint8_t s = u8();
                int8_t v = (int8_t)u8();
                extra = "slot " + formatInt(s) + (op == OP_LOCAL_ADD_IMM ? " += " : " -= ") +
                        formatInt(v);
                break;
            }
            case OP_LEND: {
                uint8_t dstG = u8();
                uint16_t dst = u16();
                uint8_t srcG = u8();
                uint16_t src = u16();
                const Value& dn = constAt(dst);
                const Value& sn = constAt(src);
                extra = std::string(dstG ? "global " : "slot ") +
                        (dstG ? (dn.o ? dn.o->str : std::string("?")) : formatInt(dst)) + " := " +
                        (srcG ? (sn.o ? sn.o->str : std::string("?")) : formatInt(src));
                break;
            }
            case OP_JUMP_IF_NOT_LT_LOCAL_LOCAL: {
                uint8_t a = u8();
                uint8_t b = u8();
                int16_t j = s16();
                extra = "if !(slot " + formatInt(a) + " < slot " + formatInt(b) + ") -> " +
                        formatInt((int64_t)i + j);
                break;
            }
            case OP_JUMP_IF_NOT_LT_LOCAL_IMM: {
                uint8_t a = u8();
                int8_t v = (int8_t)u8();
                int16_t j = s16();
                extra = "if !(slot " + formatInt(a) + " < " + formatInt(v) + ") -> " +
                        formatInt((int64_t)i + j);
                break;
            }
            case OP_CONVERT: {
                uint8_t kk = u8();
                extra = "kind " + formatInt(kk);
                break;
            }
            case OP_INDEX_ADD_IMM: {
                uint8_t a = u8();
                uint8_t b = u8();
                int8_t v = (int8_t)u8();
                extra = "slot " + formatInt(a) + "[" + formatInt(b) + "] += " + formatInt(v);
                break;
            }
            case OP_CALL_DIRECT: {
                uint16_t nameIdx = u16();
                uint8_t argc = u8();
                extra = "name #" + formatInt(nameIdx) + ", " + formatInt(argc) + " arg(s)";
                break;
            }
            case OP_LOCAL_ADD_LOCAL: {
                uint8_t a = u8();
                uint8_t b = u8();
                extra = "slot " + formatInt(a) + " += slot " + formatInt(b);
                break;            }
            case OP_ASSERT: { uint16_t k = u16(); extra = "\"" + constAt(k).o->str + "\""; break; }
            default: break;
        }
        std::printf("%s%5d  %5d  %-18s %s\n", pad.c_str(), (int)at, line, opName(op), extra.c_str());
    }
    for (auto& proto : ch->consts) {
        if (proto.t == VT::Function && proto.o->chunk.get() != ch.get()) disassemble(proto.o->chunk, depth + 1);
    }
}

// ---------------------------------------------------------------- AST dump
static void dumpExpr(const ExprP& e, int depth) {
    if (!e) return;
    std::string pad((size_t)depth * 2, ' ');
    const char* kind = "?";
    switch (e->kind) {
        case EK::Null: kind = "null"; break;
        case EK::Bool: kind = "bool"; break;
        case EK::Int: kind = "int"; break;
        case EK::Float: kind = "float"; break;
        case EK::Str: kind = "str"; break;
        case EK::Color: kind = "color"; break;
        case EK::Ident: kind = "ident"; break;
        case EK::This: kind = "this"; break;
        case EK::Super: kind = "super"; break;
        case EK::Children: kind = "children"; break;
        case EK::List: kind = "list"; break;
        case EK::Tuple: kind = "tuple"; break;
        case EK::Unary: kind = "unary"; break;
        case EK::Binary: kind = "binary"; break;
        case EK::Logical: kind = "logical"; break;
        case EK::Call: kind = "call"; break;
        case EK::Index: kind = "index"; break;
        case EK::Field: kind = "field"; break;
        case EK::Piecewise: kind = "piecewise"; break;
        case EK::Lambda: kind = "lambda"; break;
        case EK::Iter: kind = "iter"; break;
    }
    std::printf("%s%s %s %s\n", pad.c_str(), kind, e->name.c_str(),
                e->kind == EK::Str ? ("\"" + e->sval + "\"").c_str()
                                   : e->kind == EK::Int ? formatInt(e->ival).c_str() : "");
    dumpExpr(e->a, depth + 1);
    dumpExpr(e->b, depth + 1);
    for (auto& i : e->items) dumpExpr(i, depth + 1);
    for (auto& a : e->args) dumpExpr(a.value, depth + 1);
    for (auto& c : e->cases) { dumpExpr(c.first, depth + 1); dumpExpr(c.second, depth + 1); }
    dumpExpr(e->elseVal, depth + 1);
    dumpExpr(e->bodyExpr, depth + 1);
    if (e->children) for (auto& s : e->children->stmts) { std::printf("%s  child-stmt\n", pad.c_str()); (void)s; }
}

static void dumpStmt(const StmtP& s, int depth) {
    if (!s) return;
    std::string pad((size_t)depth * 2, ' ');
    const char* kind = "?";
    switch (s->kind) {
        case SK::Expr: kind = "expr"; break;
        case SK::New: kind = "new"; break;
        case SK::Const: kind = "const"; break;
        case SK::Del: kind = "del"; break;
        case SK::Assign: kind = "assign"; break;
        case SK::CompoundAssign: kind = "compound"; break;
        case SK::If: kind = "if"; break;
        case SK::While: kind = "while"; break;
        case SK::For: kind = "for"; break;
        case SK::Break: kind = "break"; break;
        case SK::Continue: kind = "continue"; break;
        case SK::Throw: kind = "throw"; break;
        case SK::Print: kind = "print"; break;
        case SK::Input: kind = "input"; break;
        case SK::Return: kind = "return"; break;
        case SK::Block: kind = "block"; break;
        case SK::FuncDef: kind = "func"; break;
        case SK::ClassDef: kind = "class"; break;
        case SK::FieldDecl: kind = "field"; break;
        case SK::ParentInit: kind = "parent"; break;
        case SK::Use: kind = "use"; break;
        case SK::MacroDef: kind = "macro"; break;
        case SK::Annot: kind = "annot"; break;
        case SK::State: kind = "state"; break;
        case SK::ViewDef: kind = "view"; break;
    }
    std::printf("%s%s %s %s\n", pad.c_str(), kind, s->name.c_str(), s->module.c_str());
    for (auto& a : s->annotations) std::printf("%s  [[%s]]\n", pad.c_str(), a.name.c_str());
    dumpExpr(s->expr, depth + 1);
    for (auto& a : s->args) dumpExpr(a, depth + 1);
    dumpExpr(s->target, depth + 1);
    dumpExpr(s->value, depth + 1);
    dumpExpr(s->cond, depth + 1);
    dumpExpr(s->iterable, depth + 1);
    dumpExpr(s->initExpr, depth + 1);
    if (s->body) for (auto& x : s->body->stmts) dumpStmt(x, depth + 1);
    if (s->elseBody) for (auto& x : s->elseBody->stmts) dumpStmt(x, depth + 1);
    for (auto& m : s->members) dumpStmt(m, depth + 1);
}

// ---------------------------------------------------------------- annotation checks
static void collectAnnotationNames(const std::vector<Annotation>& anns, std::vector<std::string>& out) {
    for (auto& a : anns) out.push_back(a.name);
}

static bool hasName(const std::vector<std::string>& v, const char* n) {
    for (auto& s : v) if (s == n) return true;
    return false;
}

struct AnnotationReport {
    std::vector<std::string> errors;
    std::vector<std::string> warnings;
};

static void checkAnnotationsOn(const std::vector<Annotation>& anns, const std::string& target, AnnotationReport& rep) {
    std::vector<std::string> names;
    collectAnnotationNames(anns, names);
    auto err = [&](const std::string& m) { rep.errors.push_back(target + ": " + m); };
    auto warn = [&](const std::string& m) { rep.warnings.push_back(target + ": " + m); };
    if (hasName(names, "pure") && hasName(names, "modifies"))
        err("[[pure]] conflicts with [[modifies]]");
    if (hasName(names, "noreturn") && hasName(names, "ensure"))
        err("[[noreturn]] conflicts with [[ensure: result...]]");
    if (hasName(names, "private") && hasName(names, "public"))
        err("[[private]] conflicts with [[public]]");
    if (hasName(names, "unsafe") && hasName(names, "trusted"))
        err("[[unsafe]] conflicts with [[trusted]]");
    if (hasName(names, "trusted") && hasName(names, "require"))
        warn("[[trusted]] overrides [[require]]");
}

static void checkStmtAnnotations(const StmtP& s, AnnotationReport& rep) {
    if (!s) return;
    if (!s->annotations.empty()) {
        std::string target = s->name.empty() ? "statement" : s->name;
        if (s->kind == SK::FuncDef) target = "function '" + s->name + "'";
        if (s->kind == SK::ClassDef) target = "class '" + s->name + "'";
        if (s->kind == SK::FieldDecl) target = "field '" + s->name + "'";
        checkAnnotationsOn(s->annotations, target, rep);
    }
    if (s->body) for (auto& x : s->body->stmts) checkStmtAnnotations(x, rep);
    if (s->elseBody) for (auto& x : s->elseBody->stmts) checkStmtAnnotations(x, rep);
    for (auto& m : s->members) checkStmtAnnotations(m, rep);
}

// ---------------------------------------------------------------- main
int main(int argc, char** argv) {
    // subcommands
    if (argc >= 2) {
        std::string cmd = argv[1];
        if (cmd == "repl") {
            std::vector<std::string> preload;
            for (int i = 2; i < argc; i++) if (argv[i][0] != '-') preload.push_back(argv[i]);
            return runRepl(preload);
        }
        if (cmd == "analyze") return cmdAnalyze(argc - 1, argv + 1);
        if (cmd == "analyze-suite") return cmdAnalyzeSuite(argc - 1, argv + 1);
        if (cmd == "bench") return cmdBench(argc - 1, argv + 1);
        if (cmd == "plugin") return cmdPlugin(argc - 1, argv + 1);
        if (cmd == "studio" || cmd == "ide-gui" || cmd == "gui-ide") return cmdStudio(argc - 1, argv + 1);
        if (cmd == "ide") return cmdIde(argc - 1, argv + 1);
        if (cmd == "lsp") return cmdLsp(argc - 1, argv + 1);
    }
    if (argc == 1) return runRepl({});          // no arguments: interactive session

    std::vector<std::string> files;
    std::string snippet;
    std::string mode = "run";
    std::string guiOut;
    bool dumpTokens = false, dumpAst = false, dumpBc = false, dumpAnn = false;
    bool contracts = false, guiWindow = false, guiShot = false, guiTree = false;
    std::vector<std::pair<int, int>> clicks;
    std::vector<std::string> keys;
    std::vector<std::string> plugins;          // C++ modules to load before the program runs

    for (int i = 1; i < argc; i++) {
        std::string a = argv[i];
        if (a == "run" || a == "check") { mode = a; continue; }
        if (a == "--dump-tokens") { dumpTokens = true; continue; }
        if (a == "--dump-ast") { dumpAst = true; continue; }
        if (a == "--dump-bc") { dumpBc = true; continue; }
        if (a == "--dump-annotations") { dumpAnn = true; continue; }
        if (a == "--contracts") { contracts = true; continue; }
        if (a == "--plugin" && i + 1 < argc) { plugins.push_back(argv[++i]); continue; }
        if (a == "--gui") { guiWindow = true; continue; }
        if (a == "--gui-tree") { guiTree = true; continue; }
        if (a == "--gui-shot" && i + 1 < argc) { guiOut = argv[++i]; guiShot = true; continue; }
        if (a == "--gui-click" && i + 1 < argc) {
            std::string spec = argv[++i];
            size_t comma = spec.find(',');
            if (comma == std::string::npos) { std::fprintf(stderr, "annota: --gui-click expects X,Y\n"); return 2; }
            clicks.emplace_back(std::atoi(spec.substr(0, comma).c_str()), std::atoi(spec.substr(comma + 1).c_str()));
            continue;
        }
        if ((a == "-e" || a == "--eval") && i + 1 < argc) { snippet = argv[++i]; continue; }
        if (a == "--features") {
            std::printf("contracts annotations files sys");
            if (guiAvailable()) std::printf(" gui ide");
            std::printf("\n");
            if (!guiAvailable()) std::printf("%s", noQtAdvice().c_str());
            return 0;
        }
        if (a == "--gui-key" && i + 1 < argc) {
            std::string k = argv[++i];
            keys.push_back(k == "@enter" ? std::string("\n") : k);   // @enter = Return key
            continue;
        }
        if (a == "-h" || a == "--help") {
            std::printf("usage: annota [run|check] <file.ant> [options]\n"
                        "  -e <code>            evaluate a snippet\n"
                        "  --dump-tokens        print the token stream\n"
                        "  --dump-ast           print the parsed program\n"
                        "  --dump-bc            disassemble the bytecode\n"
                        "  --dump-annotations   print the annotation index as JSON\n"
                        "  --contracts          evaluate assert/require/ensure/invariant annotations\n"
                        "  --plugin <file>       load a native plugin (see docs/ffi.md)\n"
                        "  --gui                open the view in a window (Qt build)\n"
                        "  --gui-shot <path>    render the view to a PNG file\n"
                        "  --gui-click X,Y      dispatch a synthetic click before --gui-shot\n"
                        "  --gui-key <text>     dispatch synthetic keystrokes before --gui-shot\n"
                        "  --gui-tree           print the view tree as text\n"
                        "  --features           list the optional features of this build\n"
                        "\nsubcommands:\n"
                        "  annota repl                 interactive session (also the default with no args)\n"
                        "  annota studio [file]        the graphical IDE (Qt build)\n"
                        "  annota analyze <file>       static analysis\n"
                        "  annota analyze-suite <dir>  run the checker over example fixtures\n"
                        "  annota ide <query> ...      hover / definition / rename / complete / inline / coverage\n"
                        "  annota bench                analysis performance benchmark\n"
                        "  annota lsp                  JSON-RPC language server over stdio\n");
            return 0;
        }
        if (!a.empty() && a[0] == '-') {
            std::fprintf(stderr, "annota: unknown option '%s'\n", a.c_str());
            return 2;
        }
        files.push_back(a);
    }

    std::string file;
    // ---------------------------------------------------------------- native plugins
    // A plugin is a shared library that registers functions/modules through src/ffi.hpp; the
    // interpreter needs no knowledge of it beyond this loop.
    {
        if (const char* env = std::getenv("ANNOTA_PLUGIN")) {
            std::string list = env;
            size_t start = 0;
            while (start <= list.size()) {
                size_t sep = list.find_first_of(";:", start);
                std::string one = list.substr(start, sep == std::string::npos ? std::string::npos : sep - start);
                if (!one.empty()) plugins.push_back(one);
                if (sep == std::string::npos) break;
                start = sep + 1;
            }
        }
        for (auto& pl : plugins) {
            std::string err;
            if (!ffiLoadPlugin(pl, &err)) {
                std::fprintf(stderr, "annota: %s\n", err.c_str());
                return 2;
            }
        }
    }

    std::string source;
    if (!snippet.empty()) {
        file = "<eval>";
        source = snippet;
    } else if (!files.empty()) {
        file = files[0];
        source = readFile(file);
        if (source.empty() && !fileExists(file)) {
            std::fprintf(stderr, "annota: cannot open '%s'\n", file.c_str());
            return 2;
        }
    } else {
        std::fprintf(stderr, "annota: no input file (try --help)\n");
        return 2;
    }

    std::string baseDir = dirOf(file == "<eval>" ? "." : file);
    FileModuleLoader loader(baseDir);
    MacroRegistry registry;

    Program program;
    try {
        std::vector<Token> toks = lex(source, file);
        if (dumpTokens) {
            for (size_t i = 0; i < toks.size(); i++)
                std::printf("%4d %-16s '%s'  line %d\n", (int)i, tokenName(toks[i].type), toks[i].text.c_str(), toks[i].line);
        }
        Parser parser(std::move(toks), file, &loader, &registry);
        program = parser.parse();
    } catch (CompileError& e) {
        printSourceError(file, e.line, e.message);
        return 1;
    }

    if (dumpAst) {
        for (auto& s : program.stmts) dumpStmt(s, 0);
    }

    AnnotationReport report;
    for (auto& s : program.stmts) checkStmtAnnotations(s, report);
    for (auto& w : report.warnings) std::fprintf(stderr, "%s: warning: %s\n", file.c_str(), w.c_str());
    if (!report.errors.empty()) {
        for (auto& e : report.errors) std::fprintf(stderr, "%s: error: %s\n", file.c_str(), e.c_str());
        return 1;
    }

    CompileResult compiled;
    try {
        Compiler compiler(program, file, contracts);
        compiled = compiler.compile();
        for (auto& w : compiler.warnings()) std::fprintf(stderr, "%s: warning: %s\n", file.c_str(), w.c_str());
    } catch (CompileError& e) {
        printSourceError(file, e.line, e.message);
        return 1;
    }

    if (dumpBc) disassemble(compiled.main, 0);

    if (dumpAnn) {
        std::printf("[\n");
        for (size_t i = 0; i < program.annotationIndex.size(); i++) {
            auto& r = program.annotationIndex[i];
            std::printf("  {\"name\": \"%s\", \"line\": %d, \"target\": \"%s\", \"args\": [",
                        r.ann.name.c_str(), r.ann.line, r.target.c_str());
            for (size_t j = 0; j < r.ann.args.size(); j++) {
                auto& g = r.ann.args[j];
                std::printf("%s{\"key\": \"%s\", \"text\": \"%s\"}", j ? ", " : "", g.key.c_str(), g.text.c_str());
            }
            std::printf("]}%s\n", i + 1 < program.annotationIndex.size() ? "," : "");
        }
        std::printf("]\n");
    }

    if (mode == "check") {
        std::printf("%s: %d statements, %d macros, %d annotations, %d classes - ok\n",
                    file.c_str(), (int)program.stmts.size(), (int)registry.macros.size(),
                    (int)program.annotationIndex.size(), (int)compiled.classes.size());
        return 0;
    }

    VM vm;
    vm.contracts = contracts;
    vm.mainChunk = compiled.main;
    for (auto& s : compiled.states) vm.stateNames.insert(s);
    registerBuiltins(vm);

    std::string viewName = compiled.views.empty() ? std::string() : compiled.views.back();

    // component trees are shown in a window when the build has Qt support
    const bool wantsWindow = !viewName.empty() && guiAvailable() && (guiWindow || guiShot);
    if (wantsWindow) {
        // Create the Qt application *before* running the script: `input` then asks with a
        // dialog instead of waiting for a console that a GUI program usually does not have.
        guiInit(argc, argv);
        guiInstallInput(vm);
    }
    if (guiWindow && !viewName.empty() && guiAvailable()) {
        int rc = 0;
        try {
            vm.run();
        } catch (VMError& e) {
            std::fprintf(stderr, "%s: runtime error: %s\n", file.c_str(), e.message.c_str());
            rc = 1;
        }
        if (rc != 0) return rc;
        return guiRunView(vm, viewName);
    }

    int rc = 0;
    try {
        vm.run();
    } catch (CompileError& e) {
        printSourceError(file, e.line, e.message);
        rc = 1;
    } catch (VMError& e) {
        std::fprintf(stderr, "%s: runtime error: %s\n", file.c_str(), e.message.c_str());
        std::string trace = vm.stackTrace();
        if (!trace.empty()) std::fprintf(stderr, "%s", trace.c_str());
        rc = 1;
    }

    if (!viewName.empty() && guiTree) {
        Value cls;
        if (vm.getGlobal(viewName, cls) && cls.t == VT::Class) {
            try {
                Value tree = vm.callSync(cls, {});
                vm.write(renderTree(tree));
            } catch (VMError& e) {
                std::fprintf(stderr, "%s: view error: %s\n", file.c_str(), e.message.c_str());
            }
        }
    }
    if (!viewName.empty() && guiShot) {
        int grc = guiRenderPng(vm, viewName, guiOut, clicks, keys);
        if (grc != 0) rc = grc;
    }
    if (!viewName.empty() && guiWindow && !guiAvailable()) {
        std::fprintf(stderr, "%s: 无法打开窗口：当前构建没有 Qt 支持（view '%s'）。%s",
                     file.c_str(), viewName.c_str(), noQtAdvice().c_str());
        rc = 2;
    }
    return rc;
}
